version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - kafka-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'

    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - kafka-network

  kafka-create-topic:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-create-topic
    depends_on:
      - kafka
    entrypoint: >
      bash -c 'echo "Waiting for Kafka to be ready..." && \
      while ! echo exit | nc kafka 9092; do sleep 10; done && \
      kafka-topics --create --topic topic-test --partitions 1 --replication-factor 1 --if-not-exists --zookeeper zookeeper:2181'
    networks:
      - kafka-network

networks:
  kafka-network:

volumes:
  kafka-data:
